
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------
package com.compilador.parser;


/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMA = 12;
  public static final int EXCLAMACION = 14;
  public static final int PUNTO = 11;
  public static final int SUSTANTIVO = 4;
  public static final int ARTICULO = 5;
  public static final int PRONOMBRE = 2;
  public static final int ADJETIVO = 6;
  public static final int EOF = 0;
  public static final int CONJUNCION = 9;
  public static final int error = 1;
  public static final int CONTRACCION = 10;
  public static final int PREPOSICION = 8;
  public static final int ADVERBIO = 7;
  public static final int VERBO = 3;
  public static final int INTERROGACION = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PRONOMBRE",
  "VERBO",
  "SUSTANTIVO",
  "ARTICULO",
  "ADJETIVO",
  "ADVERBIO",
  "PREPOSICION",
  "CONJUNCION",
  "CONTRACCION",
  "PUNTO",
  "COMA",
  "INTERROGACION",
  "EXCLAMACION"
  };
}

