#
# Configuracion de Cloud Translator API
#

# Proveedor:'google'
translator.api.provider=google



# Google Cloud Translation
translator.api.key=


# Configuracion de Spring Boot

server.port=8080
spring.application.name=compilador-traductor
